"""empty message

Revision ID: 567fd7ce97f6
Revises: 
Create Date: 2021-06-30 14:50:57.396473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '567fd7ce97f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('payment_methods',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('payment_method_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_methods')
    op.drop_table('members')
    # ### end Alembic commands ###
